language: java
branches:
  only:
  - develop 

scripts:
        - rm csci310.db
        - mvn flyway:migrate
        - mvn test
        - mvn jetty:run &
        - sleep 30
        - mvn -DrunCucumberTests test
