language: java
branches:
  only:
  - develop

services:     
        - docker

before_install:
        - docker build -t postgres-image .
        - docker run -d --name postgres-container -p 5433:5432 postgres-image
        - sleep 30

scripts:
        - mvn flyway:migrate
        - mvn test
